export const GET_ITEMS = "GET_ITEMS";
export const GET_BRANDS = "GET_BRANDS";
export const ADD_TO_CARD = "ADD_TO_CARD";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const FILTER_PRODUCTS_BY_TAGS = "FILTER_PRODUCTS_BY_TAGS";
